### ISSUE TITLE
dashbase web ui does NOT support https

### ISSUE THREAD

**Issue by ZongqiangZhang** [dashbase/dashbase-support#5]
https://[host]/dashboards/simple requires secure websocket (wss://),  but web ui is ws:// only.

**Comment by khou** [comment]
@ZongqiangZhang could you elaborate on your setup that requires the secure websocket connection? 
The web-ui can be ran in https mode by specifying a system configuration; this enhancement https://github.com/dashbase/dashbase-engine-web/pull/328 supports secure websocket if that configuration is enabled. However, this requires the https to listen on a port other than 9000, eg. 9443

**Comment by khou** [comment]
fixed with #328
