### ISSUE TITLE
SQL search: chart tab shows "Looks like you haven't queried for anything..."

### ISSUE THREAD

**Issue by ZongqiangZhang** [dashbase/dashbase-support#6]
1. run SQL search, e.g. SELECT * BEFORE NOW AFTER '2016-12-06 15:16:17';
2. the default "图表" chart tab shows "Looks like you haven't queried for anything. Refer to the docs for some example queries!"
3. click "查询结果" or "JSON" tab, there are couples of results.

![1](https://cloud.githubusercontent.com/assets/7486539/20995203/6bc7bad2-bd30-11e6-854d-692feea817d6.png)
![2](https://cloud.githubusercontent.com/assets/7486539/20995261/c75b2e74-bd30-11e6-8f66-4ce81d57fdbe.png)

**Comment by khou** [comment]
I've fixed the text to better represent the expected results.
Your query example does not have aggregations,
`SELECT * BEFORE NOW AFTER '2016-12-06 15:16:17';`
compared to an aggregation, eg.
`SELECT TS(DAY) BEFORE NOW AFTER '2016-12-06 15:16:17';`
